name: Checks

on:
  push:
  workflow_dispatch:
      
jobs:
  linux-gcc-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: install dependencies
      run: |
         sudo apt-get update
         sudo apt-get install ninja-build 

    - name: configure
      run: cmake --preset coverage

    - name: build
      run: cmake --build build_coverage

    - name: unit tests
      run: cd build && ctest -T test -T coverage

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    
    - name: Generate LCOV files
      run: lcov 
        --directory ./build
        --capture --output-file build/coverage.info

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: build/coverage.info
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}