name: Checks

on:
  push:
  workflow_dispatch:
      
jobs:
  linux-gcc-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: install dependencies
      run: |
         sudo apt-get update
         sudo apt-get install ninja-build gcovr

    - name: configure
      run: cmake --preset coverage

    - name: build
      run: cmake --build build_coverage

    - name: Run tests
      run: ctest -T test -T coverage --test-dir build_coverage

    - name: Report coverage
      run: gcovr
